// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdC516ePPMd3SB3ej9J1mHs7nzbiS_LC0',
    appId: '1:71941644517:android:dade2ef918bb54bba8f40c',
    messagingSenderId: '71941644517',
    projectId: 'talabyx',
    storageBucket: 'talabyx.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPyNAo_TcbaD-sMrK08n65a9UFdcu2qhA',
    appId: '1:71941644517:ios:32f024577d226983a8f40c',
    messagingSenderId: '71941644517',
    projectId: 'talabyx',
    storageBucket: 'talabyx.firebasestorage.app',
    iosClientId:
        '71941644517-ccce263ipohodqsdfm7ut8pet4bdbpiq.apps.googleusercontent.com',
    iosBundleId: 'net.octopusteam.talaby',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIQaLuiXkMmNC9DOCulA19AhDi4ZHTgJ0',
    appId: '1:71941644517:web:147b7ca7228ef702a8f40c',
    messagingSenderId: '71941644517',
    projectId: 'talabyx',
    authDomain: 'talabyx.firebaseapp.com',
    storageBucket: 'talabyx.firebasestorage.app',
    measurementId: 'G-R1PJV7GZBD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPyNAo_TcbaD-sMrK08n65a9UFdcu2qhA',
    appId: '1:71941644517:ios:32f024577d226983a8f40c',
    messagingSenderId: '71941644517',
    projectId: 'talabyx',
    storageBucket: 'talabyx.firebasestorage.app',
    iosClientId:
        '71941644517-ccce263ipohodqsdfm7ut8pet4bdbpiq.apps.googleusercontent.com',
    iosBundleId: 'net.octopusteam.talaby',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIQaLuiXkMmNC9DOCulA19AhDi4ZHTgJ0',
    appId: '1:71941644517:web:4d9abe14c7ed9266a8f40c',
    messagingSenderId: '71941644517',
    projectId: 'talabyx',
    authDomain: 'talabyx.firebaseapp.com',
    storageBucket: 'talabyx.firebasestorage.app',
    measurementId: 'G-SB4F9CP5GN',
  );
}
